### ISSUE TITLE
这是啥情况，你们有人用这个插件遇到过吗

### ISSUE THREAD

**Issue by wyongmin** [chazzjimel/newgpt_turbo#1]
[INFO][2023-07-05 06:47:28][netease_music.py:42] - content => 每日早报
[ERROR][2023-07-05 06:47:30][chat_channel.py:270] - Worker return exception: SessionManager.session_query() got an unexpected keyword argument 'add_to_history'
Traceback (most recent call last):
  File "D:\Program Files\Python\lib\concurrent\futures\thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
  File "D:\chatgpt-on-wecha\channel\chat_channel.py", line 146, in _handle
    reply = self._generate_reply(context)
  File "D:\chatgpt-on-wecha\channel\chat_channel.py", line 156, in _generate_reply
    e_context = PluginManager().emit_event(
  File "D:\chatgpt-on-wecha\plugins\plugin_manager.py", line 165, in emit_event
    instance.handlers[e_context.event](e_context, *args, **kwargs)
  File "D:\chatgpt-on-wecha\plugins\newgpt_turbo\main.py", line 85, in on_handle_context
    session = all_sessions.session_query(context, e_context["context"]["session_id"], add_to_history=False)
TypeError: SessionManager.session_query() got an unexpected keyword argument 'add_to_history'

**Comment by cheungchazz** [comment]
把bot文件替换一下主目录的bot文件夹，晚点我会更新一下RE

**Comment by wyongmin** [comment]
> 把bot文件替换一下主目录的bot文件夹，晚点我会更新一下RE

感谢。可是好像又出现新问题了。我API都有申请了。除了BING的API没有
