### ISSUE TITLE
不太懂代码。这问题都找不到出在那里了！

### ISSUE THREAD

**Issue by wyongmin** [chazzjimel/newgpt_turbo#2]
[INFO][2023-07-05 12:03:48][netease_music.py:42] - content => 音乐 朋友的心
[ERROR][2023-07-05 12:03:49][chat_channel.py:270] - Worker return exception: Error communicating with OpenAI: Invalid URL 'None/chat/completions': No scheme supplied. Perhaps you meant https://None/chat/completions?
Traceback (most recent call last):
  File "D:\Program Files\Python\lib\site-packages\openai\api_requestor.py", line 596, in request_raw
    result = _thread_context.session.request(
  File "D:\Program Files\Python\lib\site-packages\requests\sessions.py", line 573, in request
    prep = self.prepare_request(req)
  File "D:\Program Files\Python\lib\site-packages\requests\sessions.py", line 484, in prepare_request
    p.prepare(
  File "D:\Program Files\Python\lib\site-packages\requests\models.py", line 368, in prepare
    self.prepare_url(url, params)
  File "D:\Program Files\Python\lib\site-packages\requests\models.py", line 439, in prepare_url
    raise MissingSchema(
requests.exceptions.MissingSchema: Invalid URL 'None/chat/completions': No scheme supplied. Perhaps you meant https://None/chat/completions?

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "D:\Program Files\Python\lib\concurrent\futures\thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
  File "D:\chatgpt-on-wecha\channel\chat_channel.py", line 146, in _handle
    reply = self._generate_reply(context)
  File "D:\chatgpt-on-wecha\channel\chat_channel.py", line 156, in _generate_reply
    e_context = PluginManager().emit_event(
  File "D:\chatgpt-on-wecha\plugins\plugin_manager.py", line 165, in emit_event
    instance.handlers[e_context.event](e_context, *args, **kwargs)
  File "D:\chatgpt-on-wecha\plugins\newgpt_turbo\main.py", line 93, in on_handle_context
    conversation_output = self.run_conversation(input_messages, e_context)
  File "D:\chatgpt-on-wecha\plugins\newgpt_turbo\main.py", line 111, in run_conversation
    response = openai.ChatCompletion.create(
  File "D:\Program Files\Python\lib\site-packages\openai\api_resources\chat_completion.py", line 25, in create
    return super().create(*args, **kwargs)
  File "D:\Program Files\Python\lib\site-packages\openai\api_resources\abstract\engine_api_resource.py", line 153, in create
    response, _, api_key = requestor.request(
  File "D:\Program Files\Python\lib\site-packages\openai\api_requestor.py", line 288, in request
    result = self.request_raw(
  File "D:\Program Files\Python\lib\site-packages\openai\api_requestor.py", line 609, in request_raw
    raise error.APIConnectionError(
openai.error.APIConnectionError: Error communicating with OpenAI: Invalid URL 'None/chat/completions': No scheme supplied. Perhaps you meant https://None/chat/completions?
[INFO][2023-07-05 12:04:13][netease_music.py:42] - content => 星座运势 双鱼座
[ERROR][2023-07-05 12:04:14][chat_channel.py:270] - Worker return exception: Error communicating with OpenAI: Invalid URL 'None/chat/completions': No scheme supplied. Perhaps you meant https://None/chat/completions?
Traceback (most recent call last):
  File "D:\Program Files\Python\lib\site-packages\openai\api_requestor.py", line 596, in request_raw
    result = _thread_context.session.request(
  File "D:\Program Files\Python\lib\site-packages\requests\sessions.py", line 573, in request
    prep = self.prepare_request(req)
  File "D:\Program Files\Python\lib\site-packages\requests\sessions.py", line 484, in prepare_request
    p.prepare(
  File "D:\Program Files\Python\lib\site-packages\requests\models.py", line 368, in prepare
    self.prepare_url(url, params)
  File "D:\Program Files\Python\lib\site-packages\requests\models.py", line 439, in prepare_url
    raise MissingSchema(
requests.exceptions.MissingSchema: Invalid URL 'None/chat/completions': No scheme supplied. Perhaps you meant https://None/chat/completions?

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "D:\Program Files\Python\lib\concurrent\futures\thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
  File "D:\chatgpt-on-wecha\channel\chat_channel.py", line 146, in _handle
    reply = self._generate_reply(context)
  File "D:\chatgpt-on-wecha\channel\chat_channel.py", line 156, in _generate_reply
    e_context = PluginManager().emit_event(
  File "D:\chatgpt-on-wecha\plugins\plugin_manager.py", line 165, in emit_event
    instance.handlers[e_context.event](e_context, *args, **kwargs)
  File "D:\chatgpt-on-wecha\plugins\newgpt_turbo\main.py", line 93, in on_handle_context
    conversation_output = self.run_conversation(input_messages, e_context)
  File "D:\chatgpt-on-wecha\plugins\newgpt_turbo\main.py", line 111, in run_conversation
    response = openai.ChatCompletion.create(
  File "D:\Program Files\Python\lib\site-packages\openai\api_resources\chat_completion.py", line 25, in create
    return super().create(*args, **kwargs)
  File "D:\Program Files\Python\lib\site-packages\openai\api_resources\abstract\engine_api_resource.py", line 153, in create
    response, _, api_key = requestor.request(
  File "D:\Program Files\Python\lib\site-packages\openai\api_requestor.py", line 288, in request
    result = self.request_raw(
  File "D:\Program Files\Python\lib\site-packages\openai\api_requestor.py", line 609, in request_raw
    raise error.APIConnectionError(
openai.error.APIConnectionError: Error communicating with OpenAI: Invalid URL 'None/chat/completions': No scheme supplied. Perhaps you meant https://None/chat/completions?
[INFO][2023-07-05 12:07:27][netease_music.py:42] - content => 全国油价查询
[ERROR][2023-07-05 12:07:28][chat_channel.py:270] - Worker return exception: Error communicating with OpenAI: Invalid URL 'None/chat/completions': No scheme supplied. Perhaps you meant https://None/chat/completions?
Traceback (most recent call last):
  File "D:\Program Files\Python\lib\site-packages\openai\api_requestor.py", line 596, in request_raw
    result = _thread_context.session.request(
  File "D:\Program Files\Python\lib\site-packages\requests\sessions.py", line 573, in request
    prep = self.prepare_request(req)
  File "D:\Program Files\Python\lib\site-packages\requests\sessions.py", line 484, in prepare_request
    p.prepare(
  File "D:\Program Files\Python\lib\site-packages\requests\models.py", line 368, in prepare
    self.prepare_url(url, params)
  File "D:\Program Files\Python\lib\site-packages\requests\models.py", line 439, in prepare_url
    raise MissingSchema(
requests.exceptions.MissingSchema: Invalid URL 'None/chat/completions': No scheme supplied. Perhaps you meant https://None/chat/completions?

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "D:\Program Files\Python\lib\concurrent\futures\thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
  File "D:\chatgpt-on-wecha\channel\chat_channel.py", line 146, in _handle
    reply = self._generate_reply(context)
  File "D:\chatgpt-on-wecha\channel\chat_channel.py", line 156, in _generate_reply
    e_context = PluginManager().emit_event(
  File "D:\chatgpt-on-wecha\plugins\plugin_manager.py", line 165, in emit_event
    instance.handlers[e_context.event](e_context, *args, **kwargs)
  File "D:\chatgpt-on-wecha\plugins\newgpt_turbo\main.py", line 93, in on_handle_context
    conversation_output = self.run_conversation(input_messages, e_context)
  File "D:\chatgpt-on-wecha\plugins\newgpt_turbo\main.py", line 111, in run_conversation
    response = openai.ChatCompletion.create(
  File "D:\Program Files\Python\lib\site-packages\openai\api_resources\chat_completion.py", line 25, in create
    return super().create(*args, **kwargs)
  File "D:\Program Files\Python\lib\site-packages\openai\api_resources\abstract\engine_api_resource.py", line 153, in create
    response, _, api_key = requestor.request(
  File "D:\Program Files\Python\lib\site-packages\openai\api_requestor.py", line 288, in request
    result = self.request_raw(
  File "D:\Program Files\Python\lib\site-packages\openai\api_requestor.py", line 609, in request_raw
    raise error.APIConnectionError(
openai.error.APIConnectionError: Error communicating with OpenAI: Invalid URL 'None/chat/completions': No scheme supplied. Perhaps you meant https://None/chat/completions?

[INFO][2023-07-05 12:03:48][netease_music.py:42] - content => 音乐 朋友的心
[ERROR][2023-07-05 12:03:49][chat_channel.py:270] - Worker return exception: Error communicating with OpenAI: Invalid URL 'None/chat/completions': No scheme supplied. Perhaps you meant https://None/chat/completions?
Traceback (most recent call last):
  File "D:\Program Files\Python\lib\site-packages\openai\api_requestor.py", line 596, in request_raw
    result = _thread_context.session.request(
  File "D:\Program Files\Python\lib\site-packages\requests\sessions.py", line 573, in request
    prep = self.prepare_request(req)
  File "D:\Program Files\Python\lib\site-packages\requests\sessions.py", line 484, in prepare_request
    p.prepare(
  File "D:\Program Files\Python\lib\site-packages\requests\models.py", line 368, in prepare
    self.prepare_url(url, params)
  File "D:\Program Files\Python\lib\site-packages\requests\models.py", line 439, in prepare_url
    raise MissingSchema(
requests.exceptions.MissingSchema: Invalid URL 'None/chat/completions': No scheme supplied. Perhaps you meant https://None/chat/completions?

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "D:\Program Files\Python\lib\concurrent\futures\thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
  File "D:\chatgpt-on-wecha\channel\chat_channel.py", line 146, in _handle
    reply = self._generate_reply(context)
  File "D:\chatgpt-on-wecha\channel\chat_channel.py", line 156, in _generate_reply
    e_context = PluginManager().emit_event(
  File "D:\chatgpt-on-wecha\plugins\plugin_manager.py", line 165, in emit_event
    instance.handlers[e_context.event](e_context, *args, **kwargs)
  File "D:\chatgpt-on-wecha\plugins\newgpt_turbo\main.py", line 93, in on_handle_context
    conversation_output = self.run_conversation(input_messages, e_context)
  File "D:\chatgpt-on-wecha\plugins\newgpt_turbo\main.py", line 111, in run_conversation
    response = openai.ChatCompletion.create(
  File "D:\Program Files\Python\lib\site-packages\openai\api_resources\chat_completion.py", line 25, in create
    return super().create(*args, **kwargs)
  File "D:\Program Files\Python\lib\site-packages\openai\api_resources\abstract\engine_api_resource.py", line 153, in create
    response, _, api_key = requestor.request(
  File "D:\Program Files\Python\lib\site-packages\openai\api_requestor.py", line 288, in request
    result = self.request_raw(
  File "D:\Program Files\Python\lib\site-packages\openai\api_requestor.py", line 609, in request_raw
    raise error.APIConnectionError(
openai.error.APIConnectionError: Error communicating with OpenAI: Invalid URL 'None/chat/completions': No scheme supplied. Perhaps you meant https://None/chat/completions?
[INFO][2023-07-05 12:04:13][netease_music.py:42] - content => 星座运势 双鱼座
[ERROR][2023-07-05 12:04:14][chat_channel.py:270] - Worker return exception: Error communicating with OpenAI: Invalid URL 'None/chat/completions': No scheme supplied. Perhaps you meant https://None/chat/completions?
Traceback (most recent call last):
  File "D:\Program Files\Python\lib\site-packages\openai\api_requestor.py", line 596, in request_raw
    result = _thread_context.session.request(
  File "D:\Program Files\Python\lib\site-packages\requests\sessions.py", line 573, in request
    prep = self.prepare_request(req)
  File "D:\Program Files\Python\lib\site-packages\requests\sessions.py", line 484, in prepare_request
    p.prepare(
  File "D:\Program Files\Python\lib\site-packages\requests\models.py", line 368, in prepare
    self.prepare_url(url, params)
  File "D:\Program Files\Python\lib\site-packages\requests\models.py", line 439, in prepare_url
    raise MissingSchema(
requests.exceptions.MissingSchema: Invalid URL 'None/chat/completions': No scheme supplied. Perhaps you meant https://None/chat/completions?

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "D:\Program Files\Python\lib\concurrent\futures\thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
  File "D:\chatgpt-on-wecha\channel\chat_channel.py", line 146, in _handle
    reply = self._generate_reply(context)
  File "D:\chatgpt-on-wecha\channel\chat_channel.py", line 156, in _generate_reply
    e_context = PluginManager().emit_event(
  File "D:\chatgpt-on-wecha\plugins\plugin_manager.py", line 165, in emit_event
    instance.handlers[e_context.event](e_context, *args, **kwargs)
  File "D:\chatgpt-on-wecha\plugins\newgpt_turbo\main.py", line 93, in on_handle_context
    conversation_output = self.run_conversation(input_messages, e_context)
  File "D:\chatgpt-on-wecha\plugins\newgpt_turbo\main.py", line 111, in run_conversation
    response = openai.ChatCompletion.create(
  File "D:\Program Files\Python\lib\site-packages\openai\api_resources\chat_completion.py", line 25, in create
    return super().create(*args, **kwargs)
  File "D:\Program Files\Python\lib\site-packages\openai\api_resources\abstract\engine_api_resource.py", line 153, in create
    response, _, api_key = requestor.request(
  File "D:\Program Files\Python\lib\site-packages\openai\api_requestor.py", line 288, in request
    result = self.request_raw(
  File "D:\Program Files\Python\lib\site-packages\openai\api_requestor.py", line 609, in request_raw
    raise error.APIConnectionError(
openai.error.APIConnectionError: Error communicating with OpenAI: Invalid URL 'None/chat/completions': No scheme supplied. Perhaps you meant https://None/chat/completions?
[INFO][2023-07-05 12:07:27][netease_music.py:42] - content => 全国油价查询
[ERROR][2023-07-05 12:07:28][chat_channel.py:270] - Worker return exception: Error communicating with OpenAI: Invalid URL 'None/chat/completions': No scheme supplied. Perhaps you meant https://None/chat/completions?
Traceback (most recent call last):
  File "D:\Program Files\Python\lib\site-packages\openai\api_requestor.py", line 596, in request_raw
    result = _thread_context.session.request(
  File "D:\Program Files\Python\lib\site-packages\requests\sessions.py", line 573, in request
    prep = self.prepare_request(req)
  File "D:\Program Files\Python\lib\site-packages\requests\sessions.py", line 484, in prepare_request
    p.prepare(
  File "D:\Program Files\Python\lib\site-packages\requests\models.py", line 368, in prepare
    self.prepare_url(url, params)
  File "D:\Program Files\Python\lib\site-packages\requests\models.py", line 439, in prepare_url
    raise MissingSchema(
requests.exceptions.MissingSchema: Invalid URL 'None/chat/completions': No scheme supplied. Perhaps you meant https://None/chat/completions?

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "D:\Program Files\Python\lib\concurrent\futures\thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
  File "D:\chatgpt-on-wecha\channel\chat_channel.py", line 146, in _handle
    reply = self._generate_reply(context)
  File "D:\chatgpt-on-wecha\channel\chat_channel.py", line 156, in _generate_reply
    e_context = PluginManager().emit_event(
  File "D:\chatgpt-on-wecha\plugins\plugin_manager.py", line 165, in emit_event
    instance.handlers[e_context.event](e_context, *args, **kwargs)
  File "D:\chatgpt-on-wecha\plugins\newgpt_turbo\main.py", line 93, in on_handle_context
    conversation_output = self.run_conversation(input_messages, e_context)
  File "D:\chatgpt-on-wecha\plugins\newgpt_turbo\main.py", line 111, in run_conversation
    response = openai.ChatCompletion.create(
  File "D:\Program Files\Python\lib\site-packages\openai\api_resources\chat_completion.py", line 25, in create
    return super().create(*args, **kwargs)
  File "D:\Program Files\Python\lib\site-packages\openai\api_resources\abstract\engine_api_resource.py", line 153, in create
    response, _, api_key = requestor.request(
  File "D:\Program Files\Python\lib\site-packages\openai\api_requestor.py", line 288, in request
    result = self.request_raw(
  File "D:\Program Files\Python\lib\site-packages\openai\api_requestor.py", line 609, in request_raw
    raise error.APIConnectionError(
openai.error.APIConnectionError: Error communicating with OpenAI: Invalid URL 'None/chat/completions': No scheme supplied. Perhaps you meant https://None/chat/completions?

[INFO][2023-07-05 12:04:13][netease_music.py:42] - content => 星座运势 双鱼座
[ERROR][2023-07-05 12:04:14][chat_channel.py:270] - Worker return exception: Error communicating with OpenAI: Invalid URL 'None/chat/completions': No scheme supplied. Perhaps you meant https://None/chat/completions?
Traceback (most recent call last):
  File "D:\Program Files\Python\lib\site-packages\openai\api_requestor.py", line 596, in request_raw
    result = _thread_context.session.request(
  File "D:\Program Files\Python\lib\site-packages\requests\sessions.py", line 573, in request
    prep = self.prepare_request(req)
  File "D:\Program Files\Python\lib\site-packages\requests\sessions.py", line 484, in prepare_request
    p.prepare(
  File "D:\Program Files\Python\lib\site-packages\requests\models.py", line 368, in prepare
    self.prepare_url(url, params)
  File "D:\Program Files\Python\lib\site-packages\requests\models.py", line 439, in prepare_url
    raise MissingSchema(
requests.exceptions.MissingSchema: Invalid URL 'None/chat/completions': No scheme supplied. Perhaps you meant https://None/chat/completions?

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "D:\Program Files\Python\lib\concurrent\futures\thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
  File "D:\chatgpt-on-wecha\channel\chat_channel.py", line 146, in _handle
    reply = self._generate_reply(context)
  File "D:\chatgpt-on-wecha\channel\chat_channel.py", line 156, in _generate_reply
    e_context = PluginManager().emit_event(
  File "D:\chatgpt-on-wecha\plugins\plugin_manager.py", line 165, in emit_event
    instance.handlers[e_context.event](e_context, *args, **kwargs)
  File "D:\chatgpt-on-wecha\plugins\newgpt_turbo\main.py", line 93, in on_handle_context
    conversation_output = self.run_conversation(input_messages, e_context)
  File "D:\chatgpt-on-wecha\plugins\newgpt_turbo\main.py", line 111, in run_conversation
    response = openai.ChatCompletion.create(
  File "D:\Program Files\Python\lib\site-packages\openai\api_resources\chat_completion.py", line 25, in create
    return super().create(*args, **kwargs)
  File "D:\Program Files\Python\lib\site-packages\openai\api_resources\abstract\engine_api_resource.py", line 153, in create
    response, _, api_key = requestor.request(
  File "D:\Program Files\Python\lib\site-packages\openai\api_requestor.py", line 288, in request
    result = self.request_raw(
  File "D:\Program Files\Python\lib\site-packages\openai\api_requestor.py", line 609, in request_raw
    raise error.APIConnectionError(
openai.error.APIConnectionError: Error communicating with OpenAI: Invalid URL 'None/chat/completions': No scheme supplied. Perhaps you meant https://None/chat/completions?

**Comment by cheungchazz** [comment]
检查api地址，开debug模式才清楚，或重启整个项目后重试

**Comment by cheungchazz** [comment]
检查openai的地址

**Comment by cheungchazz** [comment]
已修复，下一下最新的覆盖

**Comment by wyongmin** [comment]
> 已修复，下一下最新的覆盖
好的。我试试。感谢
